ut4/a3/travelroad_django/main/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('places.urls', 'places')),
]

ut4/a3/travelroad_django/places/urls.py
from django.urls import path

from . import views

app_name = 'places'

urlpatterns = [
    path('', views.index, name='index'),
    path('wished/', views.wished_places, name='wished_places'),
    path('visited/', views.visited_places, name='visited_places'),
]

ut4/a3/travelroad_django/places/models.py
from django.db import models

class Place(models.Model):
    name = models.CharField(max_length=255)
    visited = models.BooleanField()

    class Meta:
        db_table = "places"

    def __str__(self):
        return self.name

ut4/a3/travelroad_django/places/views.py
from django.shortcuts import render
from .models import Place

def index(request):
    return render(request, 'place/index.html', {})

def wished_places(request):
    wished = Place.objects.filter(visited=False)
    return render(request, 'place/wished.html', {'wished': wished})

def visited_places(request):
    visited = Place.objects.filter(visited=True)
    return render(request, 'place/visited.html', {'visited': visited})

ut4/a3/travelroad_django/places/templates/place/index.html
<h1>My Travel Bucket List</h1>

<a href="{% url 'places:wished_places' %}">Places I'd Like to Visit</a>
<br>
<a href="{% url 'places:visited_places' %}">Places I've Already Been To</a>

<p>Powered by Django</p>

ut4/a3/travelroad_django/places/templates/place/visited.html
<h2>Places I've Already Been To</h2>

<ul>
  {% for place in visited %}
  <li>{{ place }}</li>
  {% endfor %}
</ul>

ut4/a3/travelroad_django/places/templates/place/whised.html
<h2>Places I'd Like to Visit</h2>

<ul>
  {% for place in wished %}
  <li>{{ place }}</li>
  {% endfor %}
</ul>

ut4/a3/travelroad_django/places/templates/place/wished.html
<h2>Places I'd Like to Visit</h2>

<ul>
  {% for place in wished %}
  <li>{{ place }}</li>
  {% endfor %}
</ul>